// app/routes/login.tsx
import { useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { login } from "~/services/user.service";
import { Button } from "primereact/button";

import { useNavigate } from "react-router";
import { InputText } from "primereact/inputtext";
import { useSelector } from "react-redux";
import LoaderActions from "~/enums/loader.enum";
import { enable, disable } from "~/services/loader.service";
import type { AuthToken } from "~/models/Auth.model";
import type { Exception } from "~/exception/app.exception";
import { useToast } from "~/components/ToastContext";

export default function LoginPage() {
  const navigate = useNavigate();
  const loaders = useSelector<{ loaders: any }, any>(state => state.loaders.loaders);
  const [searchParams] = useSearchParams();
  const [userData, setUserData] = useState<{ username: string; password: string }>({
    username: "",
    password: "",
  });
  const toast = useToast();

  const handleSubmit = (event: any) => {
    event.preventDefault();
    enable(LoaderActions.LOG_IN);
    login(userData)
      .then((token: AuthToken) => {
        toast.success(`Welcome back, ${token.user.name}!`, "Login Successful");
        navigate(searchParams.get("redirection")!);
      })
      .catch((err: Exception) => {})
      .finally(() => {
        disable(LoaderActions.LOG_IN);
      });
  };

  return (
    <div className="flex justify-center items-center min-h-[80vh] py-8">
      <div className="bg-card p-10 rounded-xl shadow-nav w-full max-w-[400px] text-center">
        <h1 className="mb-6 text-primary text-xl font-bold">Login</h1>

        <form className="text-left">
          <div className="mb-5">
            <label htmlFor="username" className="block mb-2 font-medium text-chatMsg">
              Username
            </label>
            <InputText
              id="username"
              type="text"
              name="username"
              value={userData.username}
              required
              className="w-full"
              onChange={e => {
                setUserData({ ...userData, username: e.target.value });
              }}
            />
          </div>
          <div className="mb-5">
            <label htmlFor="password" className="block mb-2 font-medium text-chatMsg">
              Password
            </label>
            <InputText
              id="password"
              type="password"
              name="password"
              value={userData.password}
              onChange={e => {
                setUserData({ ...userData, password: e.target.value });
              }}
              required
              autoComplete="current-password"
              className="w-full"
            />
          </div>
          <Button
            loading={loaders[LoaderActions.LOG_IN]}
            icon="pi pi-user"
            onClick={handleSubmit}
            label="Log in"
          />
        </form>
        <p className="mt-6 text-sm text-indigo-300">
          Don&apos;t have an account?{" "}
          <Link to="/register" className="text-primary font-medium hover:underline">
            Register
          </Link>
        </p>
      </div>
    </div>
  );
}

// src/app/routes/login/login.component.ts
import { Component } from '@angular/core';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { UserService } from '../../services/user.service';
import { InputText } from 'primeng/inputtext';
import { InputGroup } from 'primeng/inputgroup';
import { Button } from 'primeng/button';
import { InputGroupAddon } from 'primeng/inputgroupaddon';
import { LoaderService } from '../../services/loader.service';
import LoaderActions from '../../enums/loader.enum';
import { ToastService } from '../../services/toast.service';
import { Exception } from '../../exception/app.exception';
import { Router } from '@angular/router';
import { NgOptimizedImage } from '@angular/common';
import { FloatLabel } from 'primeng/floatlabel';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [
    ReactiveFormsModule,
    InputText,
    InputGroup,
    Button,
    InputGroupAddon,
    NgOptimizedImage,
    FloatLabel,
  ],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
})
export class LoginComponent {
  loginForm: FormGroup;

  constructor(
    private fb: FormBuilder,
    private userService: UserService,
    private toast: ToastService,
    protected loaders: LoaderService,
    protected router: Router,
  ) {
    this.loginForm = this.fb.group({
      username: ['', Validators.required],
      password: ['', Validators.required],
    });
  }

  onSubmit() {
    if (this.loginForm.valid) {
      try {
        this.loaders.enable(LoaderActions.LOG_IN);
        this.userService.login(this.loginForm.value).subscribe({
          next: (user) => {
            this.loaders.disable(LoaderActions.LOG_IN);
            this.toast.success(`Login Successful`, `Welcome back ${user.name}`);
            this.loginForm.reset();
            this.router.navigate(['']);
          },
          error: (error: Exception) => {
            this.loaders.disable(LoaderActions.LOG_IN);
            this.toast.error(`Login Failed`, error.message);
          },
        });
      } catch (error: Exception | Error | any) {
        this.loaders.disable(LoaderActions.LOG_IN);
        this.toast.error(`Login Failed`, error.message);
      }
    }
  }

  protected readonly LoaderActions = LoaderActions;
}

<div class="login w-full h-[80%] flex items-center justify-center">
  <form
    class="p-[32px] w-full max-w-[480px] border border-gray-500 rounded-lg"
    [formGroup]="loginForm"
    (ngSubmit)="onSubmit()"
  >
    <p-input-group class="my-4">
      <p-inputgroup-addon>
        <i class="pi pi-at"></i>
      </p-inputgroup-addon>
      <p-floatlabel variant="on">
        <input name="username" id="username" pInputText formControlName="username" type="text" />
        <label for="username">Enter Username*</label>
      </p-floatlabel>
    </p-input-group>
    <p-input-group class="my-4">
      <p-inputgroup-addon>
        <i class="pi pi-lock"></i>
      </p-inputgroup-addon>
      <p-floatlabel variant="on">
        <input
          name="password"
          id="password"
          pInputText
          formControlName="password"
          type="password"
        />
        <label for="password">Enter Password*</label>
      </p-floatlabel>
    </p-input-group>
    <div class="flex flex-col w-full gap-2 mt-4">
      <p-button
        icon="pi pi-lock"
        [loading]="loaders.isLoading(LoaderActions.LOG_IN)"
        type="submit"
        label="LOG IN"
        [rounded]="true"
        styleClass="w-full"
      />

      <p-button
        [rounded]="true"
        icon="pi pi-user"
        [loading]="loaders.isLoading(LoaderActions.LOG_IN)"
        label="SIGN IN"
        outlined
        styleClass="w-full"
        (click)="router.navigate(['register'])"
      />
    </div>
    <div class="w-full text-center my-2">OR</div>
    <div class="flex justify-center item-center w-full gap-1">
      <div class="google">
        <button>
          <img
            class="w-[32px] h-[32px] rounded-full"
            ngSrc="/images/google.svg"
            alt="Google Login"
            height="24"
            width="24"
          />
        </button>
      </div>
      <div class="github">
        <button>
          <img
            class="w-[32px] h-[32px] rounded-full"
            ngSrc="/images/github.svg"
            alt="GitHub Login"
            height="96"
            width="98"
          />
        </button>
      </div>
      <i class="microsoft">
        <button>
          <img
            class="w-[32px] h-[32px] rounded-full"
            ngSrc="/images/microsoft.svg"
            alt="Microsoft Login"
            height="16"
            width="16"
          />
        </button>
      </i>
    </div>
  </form>
</div>
