// app/components/Navbar.tsx
import { NavLink, useLocation } from "react-router";
import { useRef, useEffect, useState } from "react";

export default function Navbar() {
  const navLinks = [
    { to: "/", label: "Home" },
    { to: "/chat", label: "Chat" },
    // { to: "/h6502", label: "H6502" },
    { to: "/workspace", label: "Workspace" },
  ];

  const location = useLocation();
  const [underlineStyle, setUnderlineStyle] = useState({ left: 0, width: 0 });
  const linkRefs = useRef<(HTMLAnchorElement | null)[]>([]);

  useEffect(() => {
    const activeIdx = navLinks.findIndex(link => link.to === location.pathname);
    const activeRef = linkRefs.current[activeIdx];
    if (activeRef) {
      const rect = activeRef.getBoundingClientRect();
      const parentRect = activeRef.parentElement?.parentElement?.getBoundingClientRect();
      if (parentRect) {
        setUnderlineStyle({
          left: rect.left - parentRect.left,
          width: rect.width,
        });
      }
    }
  }, [location.pathname]);

  return (
    <nav className="bg-card shadow-nav rounded-lg mx-auto max-w-[900px] px-8 flex items-center justify-between min-h-[56px] my-4">
      <div className="h-8 w-8 mr-3 rounded-lg shadow-cardDark object-cover bg-cardDark" />
      <div className="relative flex-1">
        <ul className="flex gap-4 list-none m-0 p-0">
          {navLinks.map((link, idx) => (
            <li className="rounded transition hover:bg-cardDark hover:shadow-md" key={link.to}>
              <NavLink
                className={({ isActive }) =>
                  `inline-block text-primary font-medium text-base px-3.5 py-2 rounded transition-colors ${isActive ? "text-accent" : ""} hover:bg-primary hover:text-cardDark no-underline`
                }
                to={link.to}
                ref={el => {
                  linkRefs.current[idx] = el;
                }}
              >
                {link.label}
              </NavLink>
            </li>
          ))}
        </ul>
        <div
          className="absolute bottom-0 h-1 rounded bg-gradient-to-r from-accent via-primary to-indigo-400 transition-all z-10"
          style={{ left: underlineStyle.left, width: underlineStyle.width }}
        ></div>
      </div>
      <button className="relative z-10 bg-gradient-to-r from-accent via-primary to-indigo-400 bg-[length:300%_300%] text-white border-none rounded-xl px-6 py-2 text-base font-semibold cursor-pointer ml-4 h-11 shadow-btn flex items-center justify-center overflow-hidden transition-shadow animate-gradient-move disabled:bg-bg-muted disabled:text-chatBtnDisabledText disabled:cursor-not-allowed">
        SIGN IN
      </button>
    </nav>
  );
}

// src/app/components/navbar/navbar.component.ts
import { Component, inject, signal } from '@angular/core';
import { RouterModule, Router, RouterLinkActive } from '@angular/router';
import { NgClass } from '@angular/common';
import { MatButton } from '@angular/material/button';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [RouterModule, RouterLinkActive, NgClass, MatButton],
  templateUrl: './navbar.component.html',
})
export class NavbarComponent {
  private router = inject(Router);

  navLinks = [
    { to: '/', label: 'Home' },
    { to: '/chat', label: 'Chat' },
    { to: '/workspace', label: 'Workspace' },
  ];

  isActive(link: string) {
    return this.router.isActive(link, {
      paths: 'exact',
      queryParams: 'ignored',
      fragment: 'ignored',
      matrixParams: 'ignored',
    });
  }
}

<nav
        class="bg-surface-card shadow-md rounded-md mx-auto max-w-3xl px-content flex items-center justify-between min-h-[56px] my-4"
>
    <div class="h-8 w-8 mr-inline rounded-md shadow-md object-cover bg-surface-d"></div>

    <div class="relative flex-1">
        <ul class="flex gap-4 list-none m-0 p-0">
            @for (link of navLinks; track link) {
                <li class="rounded-md transition-colors hover:bg-surface-d">
                    <a
                            [routerLink]="link.to"
                            routerLinkActive="text-primary"
                            [routerLinkActiveOptions]="{ exact: link.to === '/' }"
                            #rla="routerLinkActive"
                            (mouseenter)="updateUnderline($event.target)"
                            class="inline-block font-inter font-medium text-base px-3.5 py-2 rounded-md transition-colors text-text hover:bg-primary hover:text-primary-color-text focus:outline-none focus:ring-2 focus:ring-primary"
                            [ngClass]="{ 'text-text-secondary': !rla.isActive }"
                            [attr.aria-current]="isActive(link.to) ? 'page' : null"
                    >
                        {{ link.label }}
                    </a>
                </li>
            }
        </ul>

        <div
                class="absolute bottom-0 h-1 rounded-md bg-gradient-to-r from-accent via-primary to-indigo-400 transition-all z-10"
                [style.left]="underlineStyle().left"
                [style.width]="underlineStyle().width"
        ></div>
    </div>

    <p-button
            icon="pi pi-user-plus"
            label="Sign in"
            class="font-inter bg-primary text-primary-color-text px-4 py-2 border-none shadow focus:ring-2 focus:ring-primary"
    />
</nav>
