// src/app/components/terminal/terminal.component.ts
// terminal.component.ts
import {
  Component,
  ElementRef,
  effect,
  signal,
  viewChild,
  PLATFORM_ID,
  inject,
} from '@angular/core';
import { CommonModule, isPlatformBrowser } from '@angular/common';
import { FormControl, FormsModule, ReactiveFormsModule } from '@angular/forms';

import { UserService } from '../../services/user.service';

type LineType = 'input' | 'output' | 'system';

interface Line {
  id: string;
  text: string;
  type: LineType;
  timestamp?: number;
}

@Component({
  selector: 'app-terminal',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, FormsModule],
  templateUrl: './terminal.component.html',
})
export class TerminalComponent {
  maxLines = 1000;

  lines = signal<Line[]>([]);
  history = signal<string[]>([]);

  inputCtrl = new FormControl('', { nonNullable: true });

  container = viewChild<ElementRef<HTMLDivElement>>('container');
  inputEl = viewChild<ElementRef<HTMLInputElement>>('inputEl');

  private platformId = inject(PLATFORM_ID);

  constructor(protected userService: UserService) {
    effect(() => {
      this.lines();
      if (isPlatformBrowser(this.platformId)) {
        queueMicrotask(() => {
          const c = this.container()?.nativeElement;
          if (c) c.scrollTop = c.scrollHeight;
        });
      }
    });

    // subscribe shell output
    // shellClient.onData(({ data, timestamp }: { data: string; timestamp: number }) => {
    //   data.split('\n').forEach((line) => {
    //     if (line.trim()) this.appendLine(line, 'output', timestamp);
    //   });
    // });
  }

  private appendLine(text: string, type: LineType = 'output', timestamp?: number) {
    if (isPlatformBrowser(this.platformId)) {
      this.lines.update((prev) => {
        const next = [...prev, { id: crypto.randomUUID(), text, type, timestamp }];
        return next.length > this.maxLines ? next.slice(-this.maxLines) : next;
      });
    }
  }

  private runCommand(raw: string) {
    const cmd = raw.trim();
    if (!cmd) return;
    this.appendLine(`${this.userService.getUserData()?.username} ${cmd}`, 'input', Date.now());
    // shellClient.send(cmd);
    this.history.update((h) => [cmd, ...h].slice(0, 200));
  }

  handleSubmit() {
    const value = this.inputCtrl.value.trim();
    if (!value) {
      this.inputCtrl.setValue('');
      return;
    }
    this.runCommand(value);
    this.inputCtrl.setValue('');
  }

  handleKeyDown(e: KeyboardEvent) {
    if (e.key === 'Enter') {
      e.preventDefault();
      this.handleSubmit();
      return;
    }
    if (e.key === 'ArrowUp') {
      e.preventDefault();
      // TODO: implement history navigation
    }
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      // TODO: implement history navigation
    }
    if (e.ctrlKey && e.key.toLowerCase() === 'c') {
      e.preventDefault();
      this.appendLine('^C', 'system', Date.now());
      this.inputCtrl.setValue('');
    }
  }
}

<div class="flex flex-col h-full min-h-80 max-h-180 w-full rounded-t-xl border-t shadow-lg">
  <div class="flex items-center justify-between gap-2 px-3 py-2">
    <div class="flex items-center gap-2">
      <span class="h-3 w-3 rounded-full inline-block bg-[red]"></span>
      <span class="h-3 w-3 rounded-full inline-block bg-[orange]"></span>
      <span class="h-3 w-3 rounded-full inline-block bg-[green]"></span>
      <div class="ml-2 text-sm font-medium opacity-90">terminal</div>
    </div>
    <div class="text-xs opacity-70">/ web • demo</div>
  </div>

  <div #container class="flex-1 overflow-y-auto px-4 py-3">
    <div class="flex flex-col gap-2 font-mono text-sm">
      @if (lines().length === 0) {
        <div class="text-gray-400 italic">(cleared)</div>
      }
      @for (ln of lines(); track ln.id) {
        <div
          [class]="{
            'text-teal-300': ln.type === 'input',
            'text-gray-200': ln.type === 'output',
            'text-amber-300 italic': ln.type === 'system',
          }"
        >
          {{ ln.text }}
        </div>
      }
    </div>
  </div>

  <form (ngSubmit)="handleSubmit()" class="px-3 py-2">
    <div class="flex items-center gap-3">
      <div class="font-mono text-sm text-teal-300">
        {{ this.userService.getUserData()?.username }}
      </div>
      <input
        #inputEl
        type="text"
        [formControl]="inputCtrl"
        (keydown)="handleKeyDown($event)"
        placeholder="type a command..."
        class="p-2 bg-inherit font-[consolas] w-full text-inherit border-none placeholder:opacity-50"
        autocomplete="off"
        spellcheck="false"
        aria-label="Terminal input"
      />
    </div>
  </form>
</div>

// app/components/Terminal.tsx
import React, { useEffect, useRef, useState, useCallback } from "react";

import shellClient from "~/services/shell.service";
import * as userService from "~/services/user.service";

type Line = {
  id: string;
  text: string;
  type: "input" | "output" | "system";
  timestamp?: number;
};

export default function Terminal({
  prompt = `${userService.getUserData().username}@optimus:~$`,
  maxLines = 1000,
}: {
  prompt?: string;
  welcome?: string;
  maxLines?: number;
}) {
  const [lines, setLines] = useState<Line[]>(() => []);
  const [input, setInput] = useState("");
  const [history, setHistory] = useState<string[]>([]);
  const containerRef = useRef<HTMLDivElement | null>(null);
  const inputRef = useRef<HTMLInputElement | null>(null);

  useEffect(() => {
    requestAnimationFrame(() => {
      if (containerRef.current) {
        containerRef.current.scrollTop = containerRef.current.scrollHeight;
      }
    });
  }, [lines]);

  useEffect(() => {
    inputRef.current?.focus();
    const handleShellData = (data: { timestamp: number; data: string }) => {
      data.data.split("\n").forEach(line => {
        if (line.trim()) {
          appendLine(line, "output", data.timestamp);
        }
      });
    };
    shellClient.onData(handleShellData);
    return () => {
      shellClient.offData();
    };
  }, []);

  const appendLine = useCallback(
    (text: string, type: Line["type"] = "output", timestamp?: number) => {
      setLines(prev => {
        const next = [...prev, { id: crypto.randomUUID(), text, type, timestamp }];
        if (next.length > maxLines) next.splice(0, next.length - maxLines);
        return next;
      });
    },
    [maxLines]
  );

  const runCommand = useCallback(
    (raw: string) => {
      const cmd = raw.trim();
      if (!cmd) return;
      appendLine(`${prompt} ${cmd}`, "input", Date.now());
      shellClient.send(cmd);
      setHistory(h => [cmd, ...h].slice(0, 200));
    },
    [appendLine, prompt]
  );

  const handleSubmit = useCallback(
    (e?: React.FormEvent) => {
      e?.preventDefault();
      if (!input.trim()) return setInput("");
      runCommand(input);
      setInput("");
    },
    [input, runCommand]
  );

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent<HTMLInputElement>) => {
      if (e.key === "Enter") {
        e.preventDefault();
        handleSubmit();
        return;
      }
      if (e.key === "ArrowUp") {
        e.preventDefault();
      }
      if (e.key === "ArrowDown") {
        e.preventDefault();
      }
      if (e.ctrlKey && e.key.toLowerCase() === "c") {
        e.preventDefault();
        appendLine("^C", "system", Date.now());
        setInput("");
      }
    },
    [handleSubmit, history, appendLine]
  );

  return (
    <div className="flex flex-col h-full min-h-[320px] max-h-[720px] w-full rounded-t-xl border-t shadow-lg">
      <div className="flex items-center justify-between gap-2 px-3 py-2">
        <div className="flex items-center gap-2">
          <span className="h-3 w-3 rounded-full inline-block bg-[red]" />
          <span className="h-3 w-3 rounded-full inline-block bg-[orange]" />
          <span className="h-3 w-3 rounded-full inline-block bg-[green]" />
          <div className="ml-2 text-sm font-medium opacity-90">terminal</div>
        </div>
        <div className="text-xs opacity-70">/ web • demo</div>
      </div>

      <div className="flex-1 overflow-y-auto px-4 py-3" ref={containerRef}>
        <div className="flex flex-col gap-2 font-mono text-sm">
          {lines.length === 0 && <div className="text-gray-400 italic">(cleared)</div>}
          {lines.map(ln => (
            <div
              key={ln.id}
              className={
                ln.type === "input"
                  ? "text-teal-300"
                  : ln.type === "output"
                    ? "text-gray-200"
                    : ln.type === "system"
                      ? "text-amber-300 italic"
                      : ""
              }
            >
              {ln.text}
            </div>
          ))}
        </div>
      </div>

      <form onSubmit={handleSubmit} className="px-3 py-2">
        <div className="flex items-center gap-3">
          <div className="font-mono text-sm text-teal-300">{prompt}</div>
          <input
            ref={inputRef}
            value={input}
            onChange={e => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="type a command..."
            className="flex-1 bg-grey outline-none font-mono text-sm text-inherit border-none placeholder:opacity-50"
            autoComplete="off"
            spellCheck={false}
            aria-label="Terminal input"
          />
        </div>
      </form>
    </div>
  );
}
